# app/services/watcher.py
import time
import sys
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# Ensure the app package context routes correctly
ROOT_DIR = Path(__file__).parent.parent.parent.resolve()
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

from app.graph.builder import create_git_graph

class GitRepoHandler(FileSystemEventHandler):
    def __init__(self, repo_path: str):
        super().__init__()
        self.repo_path = Path(repo_path).resolve()
        self.graph = create_git_graph()
        self.is_running = False
        self.last_triggered = 0

    def on_any_event(self, event):
        if event.is_directory:
            return

        event_path = Path(event.src_path).resolve()
        
        # ─── CRITICAL GUARDS: IGNORE INTERNAL AGENT CODE ───
        # We only want to watch code changes *outside* of GitPilot's system architecture
        ignore_dirs = [".git", "__pycache__", "myenv", ".venv"]
        if any(ignored in event_path.parts for ignored in ignore_dirs):
            return

        # Ignore specific file artifacts generated by the graph execution loop
        if event_path.name in ["git_graph.png", "run_pipeline.py"]:
            return

        # ─── DEBOUNCING / COOL DOWN STRATEGY ───
        # Prevent rapid-fire duplicate disk write notifications (within 2 seconds)
        current_time = time.time()
        if current_time - self.last_triggered < 2 or self.is_running:
            return

        print(f"\n🔔 Valid File System Event: {event.event_type} -> {event_path.name}")
        self.is_running = True
        self.last_triggered = current_time
        
        try:
            initial_state = {
                "repository_path": str(self.repo_path),
                "snapshot": None,
                "plan": None,
                "execution_result": None,
                "is_verified": False,
                "messages": []
            }
            
            print("🤖 Booting Autonomous Loop...")
            self.graph.invoke(initial_state)
            
        except Exception as e:
            print(f"❌ Error during graph flow execution: {e}")
        finally:
            self.is_running = False

def start_watching(repo_path: str = "."):
    abs_path = str(Path(repo_path).resolve())
    print(f"👀 Monitoring project targets for changes: {abs_path}")
    print("System active. Press Ctrl+C to stop.")
    
    event_handler = GitRepoHandler(abs_path)
    observer = Observer()
    observer.schedule(event_handler, path=abs_path, recursive=True)
    observer.start()
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nStopping filesystem monitor...")
        observer.stop()
    observer.join()

if __name__ == "__main__":
    start_watching(".")